//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Branch_To_Product
    {
        public int productID { get; set; }
        public int DepartmentID { get; set; }
        public decimal productPrice { get; set; }
    
        public virtual department department { get; set; }
        public virtual product product { get; set; }
    }
}
