//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PITdataBaseEntities : DbContext
    {
        public PITdataBaseEntities()
            : base("name=PITdataBaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Branch> Branches { get; set; }
        public virtual DbSet<category> categories { get; set; }
        public virtual DbSet<Constant_List> Constant_List { get; set; }
        public virtual DbSet<department> departments { get; set; }
        public virtual DbSet<One_time_List> One_time_List { get; set; }
        public virtual DbSet<product> products { get; set; }
        public virtual DbSet<supermarket> supermarkets { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<Branch_To_Product> Branch_To_Product { get; set; }
        public virtual DbSet<Product_To_OneTimeList> Product_To_OneTimeList { get; set; }
    }
}
