//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class One_time_List
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public One_time_List()
        {
            this.Product_To_OneTimeList = new HashSet<Product_To_OneTimeList>();
            this.User_to_Lists = new HashSet<User_to_Lists>();
        }
    
        public int Id { get; set; }
        public int userID { get; set; }
        public System.DateTime ProductionDate { get; set; }
        public Nullable<System.DateTime> endDate { get; set; }
        public bool status { get; set; }
        public int branchID { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual user user { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product_To_OneTimeList> Product_To_OneTimeList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_to_Lists> User_to_Lists { get; set; }
    }
}
