//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_To_List
    {
        public int constantListID { get; set; }
        public int productID { get; set; }
        public int quantity { get; set; }
    
        public virtual Constant_List Constant_List { get; set; }
        public virtual product product { get; set; }
    }
}
